
ln -s gthumb.png org.gnome.gThumb.png
ln -s celluloid.png io.github.celluloid_player.Celluloid.png
ln -s celluloid.png io.github.GnomeMpv.png
ln -s mpv.png mpv-icon-8bit-64x64.png
ln -s firewall.png gufw.png
ln -s utilities-terminal.png terminal.png
ln -s utilities-terminal.png org.gnome.Terminal.png
ln -s utilities-terminal.png gnome-terminal.png
ln -s calculator.png org.gnome.Calculator.png
ln -s gedit.png org.gnome.gedit.png
ln -s schildichat.png chat.schildi.desktop.png
ln -s telegram.png web-telegram.png
ln -s telegram.png org.telegram.desktop.png
ln -s telegram.png unity-webapps-telegram.png
ln -s mindustry.png com.github.Anuken.Mindustry.png
ln -s ppsspp.png org.ppsspp.PPSSPP.png
ln -s shatteredpixel.png com.shatteredpixel.shatteredpixeldungeon.png
ln -s inkscape.png org.inkscape.Inkscape.png
ln -s apostrophe.png org.gnome.gitlab.somas.Apostrophe.png
ln -s settings.png preferences.png
ln -s settings.png gnome-settings.png
ln -s settings.png preferences-desktop.png
ln -s settings.png org.gnome.Settings.png
ln -s contacts.png org.gnome.Contacts.png
ln -s contacts.png org.gnome.ContactsDevel.png
ln -s email.png org.gnome.Evolution.png
ln -s email.png org.gnome.Geary.png
ln -s email.png evolution.png
ln -s camera.png Webcam.png
ln -s camera.png webcam.png
ln -s camera.png photo.png
ln -s camera.png camera-photo.png
ln -s kdeconnect.png org.gnome.Shell.Extensions.GSConnect.png
ln -s libreoffice.png libreoffice-main.png
ln -s libreoffice.png libreoffice-startcenter.png
ln -s libreoffice.png libreoffice3.png
ln -s libreoffice.png libreoffice3-main.png
ln -s libreoffice.png libreoffice3-startcenter.png
ln -s libreoffice.png libreoffice34.png
ln -s libreoffice.png libreoffice34-main.png
ln -s libreoffice.png org.libreoffice.LibreOffice-startcenter.png
ln -s libreoffice-writer.png libreoffice3-writer.png
ln -s libreoffice-writer.png libreoffice34-writer.png
ln -s libreoffice-writer.png org.libreoffice.LibreOffice-writer.png
ln -s libreoffice-draw.png libreoffice3-draw.png
ln -s libreoffice-draw.png libreoffice34-draw.png
ln -s libreoffice-draw.png org.libreoffice.LibreOffice-draw.png
ln -s libreoffice-math.png libreoffice3-math.png
ln -s libreoffice-math.png libreoffice34-math.png
ln -s libreoffice-math.png org.libreoffice.LibreOffice-math.png
ln -s libreoffice-base.png libreoffice3-base.png
ln -s libreoffice-base.png libreoffice34-base.png
ln -s libreoffice-base.png org.libreoffice.LibreOffice-base.png
ln -s libreoffice-calc.png libreoffice3-calc.png
ln -s libreoffice-calc.png libreoffice34-calc.png
ln -s libreoffice-calc.png org.libreoffice.LibreOffice-calc.png
ln -s libreoffice-impress.png libreoffice3-impress.png
ln -s libreoffice-impress.png libreoffice34-impress.png
ln -s libreoffice-impress.png org.libreoffice.LibreOffice-impress.png
ln -s gnome-weather.png org.gnome.Weather.png
ln -s gnome-weather.png my-weather-indicator.png
ln -s gnome-weather.png org.gnome.Weather.Application.png
ln -s gnome-weather.png org.gnome.WeatherDevel.png
ln -s freeminer.png minecraft.png
ln -s freeminer.png minecraft-launcher.png
ln -s cavestory.png com.gitlab.coringao.cavestory-nx.png
ln -s blender.png org.blender.Blender.png
ln -s gucharmap.png accessories-character-map.png
ln -s gucharmap.png gnome-character-map.png
ln -s clock.png org.gnome.clocks.png
ln -s clock.png gnome-clocks.png
ln -s web-wikipedia.png com.github.hugolabe.Wike.png
ln -s citra.png org.citra_emu.citra.png
ln -s mgba.png io.mgba.mGBA.png
ln -s menu.png alacarte.png
ln -s menu.png menulibre.png
ln -s screenshot.png org.gnome.Screenshot.png
ln -s system-monitor.png org.gnome.SystemMonitor.png
ln -s mupen64plus.png mupen64plus-qt.png
ln -s org.gnome.Epiphany.png epiphany.png
ln -s bluetooth.png preferences-bluetooth.png
ln -s cinnamon-virtual-keyboard.png cs-keyboard.png
ln -s org.gnome.Extensions.png cs-extensions.png
ln -s org.gnome.Rhythmbox.png cs-sound.png
ln -s preferences-system.png cs-general.png
ln -s contacts.png cs-user.png
ln -s preferences-system.png system-settings.png
ln -s preferences-desktop-locale.png preferences-locale.png
ln -s preferences-desktop-locale.png cs-language.png
ln -s preferences-desktop-font.png cs-fonts.png
ln -s clock.png cs-date-time.png
ln -s org.gnome.seahorse.Application.png cs-privacy.png
ln -s preferences-desktop-accessibility.png cs-universal-access.png
ln -s cs-windows.png preferences-system-windows.png
ln -s network-workgroup.png cs-network.png
ln -s network-workgroup.png nm-device-wireless.png
ln -s kde.png desktop-enviroment-kde.png
ln -s package.png org.gnome.ArchiveManager.png
ln -s calendar.png org.gnome.Calendar.png
ln -s org.gnome.Extensions.png org.gnome.Shell.Extensions.png
ln -s gnome.png org.gnome.ChromeGnomeShell.png
ln -s gnome.png desktop-enviroment-gnome.png
ln -s mumble.png info.mumble.Mumble.png
ln -s gnote.png org.gnome.Notes.png
ln -s gnote.png org.gnome.Gnote.png
ln -s minetest.png net.minetest.Minetest.png
ln -s org.mozilla.firefox.png firefox.png
ln -s org.mozilla.firefox.png firefox-esr.png
ln -s arduino-arduinoide.png arduino.png
ln -s arduino-arduinoide.png arduino-ide.png
ln -s arduino-arduinoide.png cc.arduino.arduinoide.png
ln -s chromium.png com.github.Eloston.UngoogledChromium.png
ln -s signal.png org.signal.Signal.png
ln -s signal.png signal-desktop.png
ln -s steam.png com.valvesoftware.Steam.png
ln -s codeblocks.png org.codeblocks.codeblocks.png
ln -s cs-notifications.png preferences-system-notifications.png
ln -s chromium.png chromium-browser.png
ln -s firefox-developer.png firefox-developer-icon.png
ln -s kdenlive.png org.kde.kdenlive.png
ln -s org.gnome.Nautilus.png org.gnome.NautilusDevel.png
ln -s color-selector.png org.gnome.design.Contrast.png
ln -s audacity.png org.audacityteam.Audacity.png
ln -s com.discordapp.Discord.png discord.png
ln -s mintstick.png drive-removable-media.png
ln -s cs-sound.png multimedia-volume-control.png
ln -s application-x-executable.png system-run.png
ln -s openjdk-8.png openjdk-6.png
ln -s openjdk-8.png openjdk-7.png
ln -s openjdk-8.png openjdk-9.png
ln -s openjdk-8.png openjdk-11.png
ln -s openjdk-8.png java-1.8.0-openjdk.png
ln -s gtk-select-color.png cs-color.png
ln -s gtk-select-color.png preferences-color.png
ln -s code.png visual-studio-code.png
ln -s code.png code-oss.png
ln -s code.png com.visualstudio.code.png
ln -s code-insiders.png visual-studio-code-insiders.png
ln -s pavucontrol.png org.pulseaudio.pavucontrol.png
ln -s kolourpaint.png org.kde.kolourpaint.png
ln -s system-monitor.png utilities-system-monitor.png
ln -s org.gnome.Rhythmbox.png rhythmbox.png
ln -s klavaro.png net.sourceforge.Klavaro.png
ln -s gtk-select-color.png org.gnome.design.Palette.png
ln -s cs-background.png preferences-desktop-wallpaper.png
ln -s mintdrivers.png org.gnome.Firmware.png
ln -s org.gnome.Calendar.png gnome-calendar.png
ln -s neverball.png org.neverball.Neverball.png
ln -s neverputt.png org.neverball.Neverball.Neverputt.png
ln -s stepmania.png com.stepmania.StepMania.png
ln -s chibitracker.png com.github.reduz.ChibiTracker.png
ln -s supertuxkart.png net.supertuxkart.SuperTuxKart.png
ln -s org.gnome.meld.png org.gnome.Meld.png
ln -s org.kde.krita.png krita.png
ln -s exfalso.png io.github.quodlibet.ExFalso.png
ln -s keepassxc.png org.keepassxc.KeePassXC.png
ln -s lmms.png io.lmms.LMMS.png
ln -s glade.png org.gnome.Glade.png
ln -s menu.png org.bluesabre.MenuLibre.png
ln -s chrome.png com.google.Chrome.png
ln -s org.gnome.TextEditor.png org.gnome.TextEditor.Devel.png
ln -s org.gnome.World.Highscore.png org.gnome.World.Highscore.Devel.png
ln -s gimp.png org.gimp.GIMP.png
ln -s org.freedesktop.GnomeAbrt.png abrt.png
ln -s linuxmint.png mintwelcome.png
ln -s preferences-symbolic.symbolic.png preferences-other-symbolic.symbolic.png
ln -s preferences-symbolic.symbolic.png preferences-system-symbolic.png
ln -s syncthing.png me.kozec.syncthingtk.png
ln -s rrootage.png com.abagames.rRootage.png
ln -s anki.png net.ankiweb.Anki.png
ln -s goa-account-lastfm.png lastfm.png
